title: Image Captioning
type: community
group: Computer Vision
image: /static/templates/image-captioning.png
details: <h1>Write text describing the image</h1>
config: |
  <View>
    <Image name="image" value="$captioning"/>
    <Header value="تصویر را شرح دهید:"/>
    <TextArea name="caption" toName="image" placeholder="شرح تصویر را اینجا وارد کنید..."
              rows="5" maxSubmissions="1"/>
  </View>

