title: Pairwise classification
type: community
group: Ranking & Scoring
image: /static/templates/pairwise-classification.png
details: <h1>یکی از دو آیتم را انتخاب کنید</h1>
config: |
  <View>
    <Header>یکی از دو آیتم را انتخاب کنید</Header>
    <Pairwise name="pw" toName="text1,text2" />
    <Text name="text1" value="$pairText1" />
    <Text name="text2" value="$pairText2" />
  </View>
